In [ ]:
import nltk

nltk.download("gutenberg")

[nltk_data] Downloading package gutenberg to
[nltk_data]     /Users/himanshupragyan/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


True

In [ ]:
from nltk.corpus import gutenberg
import pandas as pd

data = gutenberg.raw("shakespeare-hamlet.txt")
with open("hamlet.txt", "w") as f:
    f.write(str(data))

In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [ ]:
with open("hamlet.txt", "r") as f:
    text = f.read().lower()
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1
print(total_words)

4818


In [18]:
l = tokenizer.texts_to_sequences([text])[0]
print(len(text[0]))
print(l[:10])

1
[1, 687, 4, 45, 41, 1886, 1887, 1888, 1180, 1889]


In [8]:
input_sequences = []
flag=True
for line in text.split("\n"):
    if flag:
        print(line)
        flag=False
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[: i + 1]
        input_sequences.append(n_gram_sequence)
print(input_sequences[:5])

[the tragedie of hamlet by william shakespeare 1599]
[[1, 687], [1, 687, 4], [1, 687, 4, 45], [1, 687, 4, 45, 41], [1, 687, 4, 45, 41, 1886]]


In [19]:
Max_sequence_len = max([len(x) for x in input_sequences])

In [20]:
input_sequences = np.array(pad_sequences(input_sequences, maxlen=Max_sequence_len, padding="pre"))
print(input_sequences[:5])

[[   0    0    0    0    0    0    0    0    0    0    0    0    1  687]
 [   0    0    0    0    0    0    0    0    0    0    0    1  687    4]
 [   0    0    0    0    0    0    0    0    0    0    1  687    4   45]
 [   0    0    0    0    0    0    0    0    0    1  687    4   45   41]
 [   0    0    0    0    0    0    0    0    1  687    4   45   41 1886]]
